- Entertainment & Media:
  - Jellyfin:
    icon: /temp_file_path/jellyfin.png
    href: donthaveoneyet
    description: Watch Movies & TV Shows
    widget:
      type: jellyfin
      url: donthaveoneyet
      key: donthaveoneyet
      enableBlocks: true
      enableNowplaying: true
      enableUser: true
      enableMediaControl: true
      showEpisodeNumber: trye
      expandOneStreamToTwoRows: true
  - Navidrome:
    icon: /temp_file_path/navidrome.png
    href: donthaveoneyet
    description: Listen To Music
    widget:
      type: navidrome
      url: donthaveoneyet
      key: donthaveoneyet
  - Radarr:
    icon: /temp_file_path/radarr.png
    href: donthaveoneyet