title: PiLab Dashboard
favicon: /temp_file_path/favicon.png
background: /temp_file_path/background.png
cardblur: xs
theme: dark
colour: slate
headerStyle: boxed
language: en

layout:
  Productivity & Documents:
    tab: First
    style: row
    columns: 1
  Entertainment & Media:
    tab: Second
    style: row
    columns: 1
  Device & Connectivity:
    tab: Third
    style: row
    column: 1

quicklaunch:
  probider: duckduckgo
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: true
  hideVisitURL: false
  target: _self